Add testing scenario infrastructure
cxsca/sca-agent pull request #11
Opened 2021-02-01 11:25 UTC by dbolharovcmx

2021-02-01 11:25 UTC, dbolharovcmx commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create initial infrastructure for agent scenarios testing](https://trello.com/c/kqwFKPsC/1076-create-initial-infrastructure-for-agent-scenarios-testing)

2021-02-18 16:33 UTC, SnirCm requested changes

2021-02-18 16:33 UTC, SnirCm commented on tests/customport/bundle-overrides/volumes/traefik/http/traefik.toml
> +address = ":5001"
this should stay 80

2021-02-18 16:33 UTC, SnirCm commented on tests/customport/bundle-overrides/.env.defaults
> +TRAEFIK_PORT=5001
this too should stay 80 it is the port inside the container

2021-02-18 16:33 UTC, SnirCm commented on tests/customport/bundle-overrides/.env.defaults
> +EXTERNAL_PORT=5001
changing this to 5001 is all that is needed

2021-02-18 16:33 UTC, SnirCm commented on tests/README.md
> +# Scenario Testing
👌

2021-02-19 14:54 UTC, dbolharovcmx commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add basic connectivity tests to the agent](https://trello.com/c/NXeVaCwL/1077-add-basic-connectivity-tests-to-the-agent)

2021-02-19 17:06 UTC, dbolharovcmx commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add HTTPS test to the agent](https://trello.com/c/UCpwJGXq/1078-add-https-test-to-the-agent)

2021-02-21 16:03 UTC, Snirx1 commented on tests/https/bundle-overrides/volumes/traefik/ssl/cert.crt
> +-----BEGIN CERTIFICATE-----
self signed?

2021-02-22 07:35 UTC, dbolharovcmx commented on tests/https/bundle-overrides/volumes/traefik/ssl/cert.crt
> +-----BEGIN CERTIFICATE-----
Yes, generated myself

2021-02-22 10:36 UTC, Snirx1 approved these changes

2021-02-22 11:05 UTC, yellowblood requested changes
.

2021-02-22 11:06 UTC, maor-rosenfeld requested changes
1. Move the python tests source code (and its Dockerfile) to the "tests" folder, because these tests are shared between the scenarios.
2. Avoid duplicating the entire env vars, instead only specify the vars which you're actually overriding

2021-02-22 16:50 UTC, maor-rosenfeld reviewed
How do you run specific tests for specific scenarios?

2021-02-22 16:50 UTC, maor-rosenfeld commented on Jenkinsfile
> +                                    ws("${testName}-workspace"){
👌

2021-02-22 16:50 UTC, maor-rosenfeld commented on Jenkinsfile
> +                                        }
Can you move all this to a script file under the tests folder? Preferably a shell script file that you can also run locally without Jenkins. Easier to fix problems when you can run the same thing locally.

2021-02-22 16:50 UTC, maor-rosenfeld commented on tests/README.md
> +         |--.env.defaults
```suggestion
         |--.env
```

2021-02-22 16:50 UTC, maor-rosenfeld commented on tests/README.md
> +Environment Variables can be overwritten by adding `.env.overrides` files in the root of `bundle-overrides`.
why not just ".env"?
```suggestion
Environment Variables can be overwritten by adding `.env` files in the root of `bundle-overrides`. 
```

2021-02-22 16:50 UTC, maor-rosenfeld commented on tests/customport/docker-compose.yml
> +      AGENT-PORT: 5001
A dash in env vars is a big no no
```suggestion
      AGENT_PORT: 5001
```

2021-02-22 17:05 UTC, dbolharovcmx commented on tests/README.md
> +Environment Variables can be overwritten by adding `.env.overrides` files in the root of `bundle-overrides`.
The thing is that then `Setup.sh` is adding `.env` file during the install and there is no automatic merge for already existing `.env` file. So the `.env.overrides` just adds then the contents to the end overwritting the previous value. Not elegant at all, but no need to implement the logic on finding and replacing the values.

2021-02-23 10:07 UTC, dbolharovcmx commented
![](https://github.trello.services/images/mini-trello-icon.png) [Agent Test Infra - Refactoring](https://trello.com/c/EUyZcwNo/1104-agent-test-infra-refactoring)

2021-02-24 15:35 UTC, maor-rosenfeld approved these changes

2021-02-25 08:24 UTC, merged