Add Cx-Flow Tests
cxsca/sca-agent pull request #25
Opened 2021-03-17 15:15 UTC by dbolharovcmx

2021-03-17 15:15 UTC, dbolharovcmx commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add tests for CxFlow in SCA Agent](https://trello.com/c/HGJGXfve/1111-add-tests-for-cxflow-in-sca-agent)

2021-03-25 17:06 UTC, maor-rosenfeld commented on tests/README.md
> +
read about .gitattributes

2021-03-26 08:03 UTC, dbolharovcmx commented on tests/README.md
> +
**.gitattributes** configured as expecpected right now and is just fine. But when folks are working locally and do the modifications in that script in Windows - it appears that everything works not as expected. That line is just an attempt to warn the reader about that and save him some time.

2021-03-29 11:19 UTC, Snirx1 requested changes

2021-03-29 11:19 UTC, Snirx1 commented on tests/src/connectivity/scripts/cxflow_tests.py
> +        time.sleep(60)
maybe worth calling it's health check if it has one

2021-03-29 11:19 UTC, Snirx1 commented on tests/README.md
> +
need something that explain the problem better, also where does the script breaks in that case? what command?

2021-03-29 11:30 UTC, Snirx1 approved these changes

2021-03-29 11:58 UTC, merged