Add https support
cxsca/sca-agent pull request #3
Opened 2020-12-24 09:44 UTC by SnirCm

2020-12-24 12:22 UTC, vladkravets commented on docker-compose.yml
> +      - "443:443"
do we need mapping for both `80` and `443`? Could it depend on `TLS` env. var.?

2020-12-24 13:00 UTC, SnirCm commented on docker-compose.yml
> +      - "443:443"
you right, forgot to copy this from the old branch!

2020-12-24 13:19 UTC, vladkravets approved these changes

2020-12-28 09:27 UTC, levaizenberg-checkmarx commented on .env.defaults
> +TLS=false
<minor> oh maybe in customer facing param call it HTTPS still? somehow more common, not sure everyone understand the difference. we only use HTTPS no? or change in comment

2020-12-28 09:49 UTC, levaizenberg-checkmarx commented on docker-compose.yml
> +      - CONFIG_LOCATION=/dynamic/${TRANSFER_PROTOCOL}/traefik.toml
sorry I must be missing something - why not having one traefik.toml with 2 entrypoints?

2020-12-28 09:52 UTC, levaizenberg-checkmarx approved these changes
its a pity we couldn't manage with one traekik.toml and one volume

2020-12-29 10:11 UTC, SnirCm commented on docker-compose.yml
> +      - CONFIG_LOCATION=/dynamic/${TRANSFER_PROTOCOL}/traefik.toml
the path to the providers.file in that toml can't be set there to different locations, I couldn't find a way to load it from ENV there so I had to split it with the dynamic-config

2021-01-04 19:46 UTC, maor-rosenfeld requested changes

2021-01-04 19:46 UTC, maor-rosenfeld commented on .env.defaults
> +TLS=false
```suggestion
EXTERNAL_HOSTNAME=127.0.0.1
TRANSFER_PROTOCOL=http
TRAEFIK_PORT=80
TLS=false

# To enable HTTPS, uncomment these lines:
# TRANSFER_PROTOCOL=https
# TRAEFIK_PORT=443
# TLS=true

```

2021-01-04 19:46 UTC, maor-rosenfeld commented on .gitignore
> +!volumes/traefik/ssl/rename_to-key.key
```suggestion
# Traefik HTTPS
/volumes/traefik/ssl/*
```

2021-01-04 19:46 UTC, maor-rosenfeld commented on docker-compose.yml
> +      - ./volumes/traefik/ssl/key.key:/etc/traefik/ssl/key.key
```suggestion
      - ./volumes/traefik:/etc/traefik
```

Can you make that work?

2021-01-04 19:46 UTC, maor-rosenfeld commented on volumes/traefik/http/traefik.toml
> +directory = "/dynamic/http"
```suggestion
directory = "/etc/traefik/http"
```

2021-01-04 19:46 UTC, maor-rosenfeld commented on volumes/traefik/https/traefik.toml
> +address = ":443"
What's the point of letting the user configure a port if you're hardcoding it here?

2021-01-04 19:46 UTC, maor-rosenfeld commented on volumes/traefik/https/traefik.toml
> +insecure = true
```suggestion

```

2021-01-04 19:46 UTC, maor-rosenfeld commented on volumes/traefik/ssl/rename_to-cert.crt
> +REPLACE WITH A VALID CERT AND SAVE AS cert.cert
Don't see a point in these files.

2021-01-04 19:46 UTC, maor-rosenfeld commented on volumes/traefik/https/traefik.toml
> +defaultEntryPoints = ["https"]
I think you can convert this file to yml, and maybe join it together with the dynamic config file. I don't like all of this duplication. Make it more elegant.

2021-01-05 10:05 UTC, SnirCm commented on volumes/traefik/https/traefik.toml
> +address = ":443"
this is traeffik port I just let him configure the external port

2021-01-05 10:08 UTC, SnirCm commented on volumes/traefik/https/traefik.toml
> +defaultEntryPoints = ["https"]
it's 2 different configuration I can't merge this with the dynamic, I can try again merge the http/dynamic and https/dynamic but I think the duplication will just move inside the file instead of 2 files

2021-01-05 10:09 UTC, SnirCm commented on .env.defaults
> +TLS=false
pretty sure this won't work

2021-01-06 13:49 UTC, SnirCm commented on .env.defaults
> +TLS=false
ya this is not working

2021-01-06 14:03 UTC, SnirCm commented on volumes/traefik/https/traefik.toml
> +defaultEntryPoints = ["https"]
not possible

2021-01-06 14:12 UTC, SnirCm commented on docker-compose.yml
> +      - ./volumes/traefik/ssl/key.key:/etc/traefik/ssl/key.key
no... balagan it overrides files of traefik

2021-01-10 09:25 UTC, SnirCm commented on .gitignore
> +!volumes/traefik/ssl/rename_to-key.key
Replace them with a readme?

2021-01-10 09:26 UTC, SnirCm commented on volumes/traefik/https/traefik.toml
> +insecure = true
This is the UI I will remove before merge

2021-01-14 09:10 UTC, maor-rosenfeld approved these changes

2021-01-14 09:25 UTC, merged