Add script to kill zombie containers
cxsca/sca-agent pull request #8
Opened 2021-01-26 09:32 UTC by SnirCm

In order to test:
1. docker-compose up - start the agent
2. stop the agent
3. manually run only the minio container using his id, he should now be a zombie (try kill it should fail)
4. run the script and restart docker if on windows
5. all sca agent containers should be gone images should be intact 

in wsl you need to run it with '/bin/bash' - some linking they did to sh command make it fail 
tested on: wsl2-ubuntu, gitBash, Linux-ubuntu

2021-01-26 09:36 UTC, SnirCm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create a script that cleans hanging docker images (like minio) in the agent](https://trello.com/c/pvRM1I8a/1056-create-a-script-that-cleans-hanging-docker-images-like-minio-in-the-agent)

2021-01-26 14:32 UTC, dbolharovcmx submitted a review, later dismissed
Works for me. Good Job

2021-01-27 11:26 UTC, maor-rosenfeld requested changes
Move this script and `show-scans-status.sh` to a `tools` folder.

2021-01-27 11:26 UTC, maor-rosenfeld commented on remove-zombie-containers.sh
> +docker ps -a --no-trunc -f name=sca-agent* --format "table {{.ID}}\t{{.Names}}" || exit
If there are no running or hanging containers, just print a message and exit

2021-01-27 11:26 UTC, maor-rosenfeld commented on remove-zombie-containers.sh
> +read -n 1
This line blocks non-human executions. Add a `-y` flag to skip this.

2021-01-27 11:26 UTC, maor-rosenfeld commented on remove-zombie-containers.sh
> +cmd=$(command -v cmd.exe || echo shell)
Doesn't work for me with WSL2

```
$ ./remove-zombie-containers.sh
Removing following containers:
CONTAINER ID        NAMES
-------------------------------------------
Press any key to continue...
./remove-zombie-containers.sh: 7: read: Illegal option -n
Starting
Creating zombie container with cmd to access MobyLinuxVM
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
596ba82af5aa: Pull complete
Digest: sha256:d9a7354e3845ea8466bb00b22224d9116b183e594527fb5b6c3d30bc01a20378
Status: Downloaded newer image for alpine:latest
b35532833b8cbeb197f94f5267e5f724f2f1c8afe2d71b871850b94d409faead
docker: Error response from daemon: /dev/shm is not mounted, but must be for --ipc=host.
```

2021-01-31 08:42 UTC, SnirCm commented on remove-zombie-containers.sh
> +cmd=$(command -v cmd.exe || echo shell)
you need to run like this: /bin/bash remove-zombie-containers.sh
there is some linking in wsl to sh that make it fail

2021-01-31 08:56 UTC, SnirCm commented on remove-zombie-containers.sh
> +read -n 1
Added -s | --silence

2021-01-31 09:08 UTC, SnirCm commented on remove-zombie-containers.sh
> +docker ps -a --no-trunc -f name=sca-agent* --format "table {{.ID}}\t{{.Names}}" || exit
done

2021-01-31 09:09 UTC, SnirCm commented on remove-zombie-containers.sh
> +cmd=$(command -v cmd.exe || echo shell)
added it to the --help examples

2021-02-02 13:36 UTC, maor-rosenfeld commented on remove-zombie-containers.sh
> +cmd=$(command -v cmd.exe || echo shell)
Just change the first line of the script to `/bin/bash`.

2021-02-03 08:33 UTC, SnirCm commented on remove-zombie-containers.sh
> +cmd=$(command -v cmd.exe || echo shell)
it is only a problem on wsl2 but ok

2021-02-03 15:59 UTC, maor-rosenfeld approved these changes

2021-02-03 16:18 UTC, merged